from ml.modules.loss_functions.loss_function import LossFunction
from ml.modules.loss_functions.cross_entropy import CrossEntropyLoss
from ml.modules.loss_functions.log_likelihood import SigmoidLogLikelihood